service: was-today-better

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  handler:
    handler: handler.handler
    environment:
      FIREBASE_USER: ${env:FIREBASE_USER}
      FIREBASE_PASSWORD: ${env:FIREBASE_PASSWORD}
      FIREBASE_USER_OID: ${env:FIREBASE_USER_OID}
    events:
      - alexaSkill: amzn1.ask.skill.1ab15c41-18a8-49a9-9ea4-f58166c7f429
